use master

CREATE DATABASE TRABAJO_DIPLOMA

GO

USE TRABAJO_DIPLOMA

GO


CREATE TABLE TUTOR(
	TUT_ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TUT_NOMBRE VARCHAR(30) NOT NULL,
	TUT_APELLIDO VARCHAR(30) NOT NULL,
	TUT_TELEFONO_PRIMARIO VARCHAR(30) NOT NULL,
	TUT_TELEFONO_SECUNDARIO VARCHAR(30),
	TUT_DNI VARCHAR(30) NOT NULL UNIQUE,
	TUT_EMAIL VARCHAR(30) NOT NULL

)

CREATE TABLE MATERIA(
	MAT_ID BIGINT PRIMARY KEY NOT NULL IDENTITY (1,1),
	MAT_NOMBRE VARCHAR(20) NOT NULL UNIQUE,
	MAT_DESCRIPCION VARCHAR(50) NOT NULL,
	MAT_TIPO BIT NOT NULL,
	MAT_BORRADA BIT 
)

CREATE TABLE ORIENTACION(
	ORI_CODIGO BIGINT PRIMARY KEY IDENTITY(1,1),
	ORI_NOMBRE VARCHAR(50) NOT NULL
)
CREATE TABLE NIVEL(
	NIV_ID BIGINT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NIV_CODIGO VARCHAR(10) NOT NULL UNIQUE,
	NIV_DESCRIPCION VARCHAR(20) NOT NULL,
	NIV_ORIENTACION BIGINT FOREIGN KEY REFERENCES ORIENTACION(ORI_CODIGO)
)
CREATE TABLE MATERIA_NIVEL(
	MN_MATERIA_ID BIGINT FOREIGN KEY REFERENCES MATERIA(MAT_ID) NOT NULL,
	MN_NIVEL_ID BIGINT FOREIGN KEY REFERENCES NIVEL(NIV_ID) NOT NULL
)
CREATE TABLE DOCENTE(
	DOC_LEGAJO BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DOC_APELLIDO VARCHAR(20)  NOT NULL,
	DOC_NOMBRE VARCHAR(20)  NOT NULL,
	DOC_DNI VARCHAR(20)  NOT NULL UNIQUE,
	DOC_FECHA_NACIMIENTO DATE NOT NULL,
	DOC_DIRECCION VARCHAR(50)  NOT NULL,
	DOC_TELEFONO VARCHAR(20)  NOT NULL,
)
CREATE TABLE INASISTENCIA_DOCENTE(
	IND_DOCENTE_ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IND_FECHA DATE NOT NULL,
	IND_DVH VARCHAR(50) NOT NULL,
	IND_JUSTIFICADA BIT NOT NULL
)

CREATE TABLE MODULO(
	MOD_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	MOD_HORA_INICIO VARCHAR(10) NOT NULL,
	MOD_HORA_FINAL VARCHAR(10) NOT NULL
)

CREATE TABLE CURSO(
	CUR_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	CUR_NIVEL_ID BIGINT FOREIGN KEY REFERENCES NIVEL(NIV_ID) NOT NULL,
	CUR_CAPACIDAD BIGINT NOT NULL,
	CUR_CODIGO VARCHAR(10) NOT NULL UNIQUE,
	CUR_TURNO CHAR(1) NOT NULL,
	CUR_LETRA CHAR(1) NOT NULL,
	CUR_BORRADO BIT
)
CREATE TABLE HORARIO(
	HOR_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	HOR_DIA BIGINT NOT NULL,
	HOR_CURSO BIGINT FOREIGN KEY REFERENCES CURSO(CUR_ID) NOT NULL,
	HOR_MATERIA_ID BIGINT FOREIGN KEY REFERENCES MATERIA(MAT_ID) NOT NULL,
	HOR_DOCENTE_ID BIGINT FOREIGN KEY REFERENCES DOCENTE(DOC_LEGAJO) NOT NULL,
	HOR_MODULO_ID BIGINT FOREIGN KEY REFERENCES MODULO(MOD_ID)
)
CREATE TABLE ALUMNO(
	ALU_LEGAJO BIGINT PRIMARY KEY IDENTITY(1,1),
	ALU_APELLIDO VARCHAR(30) NOT NULL,
	ALU_NOMBRE VARCHAR(30) NOT NULL,
	ALU_FECHA_NACIMIENTO DATE NOT NULL,
	ALU_DNI VARCHAR(30) NOT NULL UNIQUE,
	ALU_CURSO BIGINT FOREIGN KEY REFERENCES CURSO(CUR_ID) NOT NULL,
	ALU_DOMICILIO VARCHAR(30) NOT NULL,
	ALU_ORIENTACION BIGINT FOREIGN KEY REFERENCES ORIENTACION(ORI_CODIGO),
	ALU_BORRADO BIT
)
CREATE TABLE INASISTENCIA_DE_ALUMNO(
	INA_ALUMNO_ID BIGINT FOREIGN KEY REFERENCES ALUMNO(ALU_LEGAJO) NOT NULL,
	INA_FECHA DATE NOT NULL,
	INA_VALOR NUMERIC(2,2) NOT NULL,
	INA_DVH VARCHAR(50) NOT NULL,
	INA_JUSTIFICADA BIT NOT NULL
)
CREATE TABLE AMONESTACION(
	AMON_ALUMNO_ID BIGINT FOREIGN KEY REFERENCES ALUMNO(ALU_LEGAJO) NOT NULL,
	AMON_FECHA DATE NOT NULL,
	AMON_MOTIVO TEXT NOT NULL,
	AMON_DVH VARCHAR(50) NOT NULL
)
CREATE TABLE ALUMNO_TUTOR(
	AT_ALUMNO_ID BIGINT FOREIGN KEY REFERENCES ALUMNO(ALU_LEGAJO) NOT NULL,
	AT_TUTOR_ID BIGINT FOREIGN KEY REFERENCES TUTOR(TUT_ID) NOT NULL
)
CREATE TABLE NOTA(
	NOTA_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	NOTA_MATERIA_ID BIGINT FOREIGN KEY REFERENCES MATERIA(MAT_ID) NOT NULL,
	NOTA_DOCENTE_ID BIGINT FOREIGN KEY REFERENCES DOCENTE(DOC_LEGAJO) NOT NULL,
	NOTA_TRIMESTRE BIGINT NOT NULL,
	NOTA_NOTA BIGINT NOT NULL,
	NOTA_CURSO_ID BIGINT FOREIGN KEY REFERENCES CURSO(CUR_ID) NOT NULL,
	NOTA_ALUMNO_ID BIGINT FOREIGN KEY REFERENCES ALUMNO(ALU_LEGAJO) NOT NULL,
	NOTA_DVH VARCHAR(50) NOT NULL,
	NOTA_BORRADO BIT NOT NULL DEFAULT 0,
)
CREATE TABLE NOTA_DE_MESA(
	NDM_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	NDM_DOCENTE_ID BIGINT FOREIGN KEY REFERENCES DOCENTE(DOC_LEGAJO) NOT NULL,
	NDM_ADJUNTO_ID BIGINT FOREIGN KEY REFERENCES DOCENTE(DOC_LEGAJO) NOT NULL,
	NDM_ALUMNO BIGINT FOREIGN KEY REFERENCES ALUMNO(ALU_LEGAJO) NOT NULL,
	NDM_CURSO_ID BIGINT FOREIGN KEY REFERENCES CURSO(CUR_ID) NOT NULL,
	NDM_FECHA DATE NOT NULL,
	NDM_LIBRO VARCHAR(10) NOT NULL,
	NDM_FOLIO VARCHAR(10) NOT NULL,
	NDM_NOTA BIGINT NOT NULL,
	NDM_MATERIA_ID BIGINT FOREIGN KEY REFERENCES MATERIA(MAT_ID),
	NDM_DVH VARCHAR(50) NOT NULL
)
CREATE TABLE PLANILLA_DE_EVALUACION(
	PDE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	PDE_ALUMNO_ID BIGINT FOREIGN KEY REFERENCES ALUMNO(ALU_LEGAJO) NOT NULL,
	PDE_NIVEL_ID BIGINT FOREIGN KEY REFERENCES NIVEL(NIV_ID) NOT NULL,
	PDE_TRIMESTRE_1 BIGINT ,
	PDE_TRIMESTRE_2 BIGINT ,
	PDE_TRIMESTRE_3 BIGINT ,
	PDE_NOTA_FINAL BIGINT ,
	PDE_CONDICION BIGINT ,
	PDE_DVH VARCHAR(50) NOT NULL,
	PDE_MATERIA_ID BIGINT FOREIGN KEY REFERENCES MATERIA(MAT_ID)
)